{ config, pkgs, ... }:

{
  home.packages = with pkgs; [
    brave-origin
    discord
    slack
    kdePackages.kdeconnect-kde
    openrazer-daemon
    kitty
    fastfetch
    mate-polkit
    polychromatic
    ffmpeg
    nextcloud-client
    ytmdesktop
    teams-for-linux
    teamspeak6-client
    lan-mouse
    prismlauncher
    easyeffects
    nwg-look
    nwg-displays
    pavucontrol
    hyprshot
    hyprwayland-scanner
    hyprland-qtutils
    hyprcursor
    tailscale
    jellyfin-desktop
    bitwarden-desktop
    audacity
    protonup-qt
    obs-studio
    qt6Packages.qtstyleplugin-kvantum
    popsicle
    streamcontroller
  ];
}
